# fly.toml app configuration file generated for searxng-dbg9na on 2025-03-26T13:15:55Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'searxng-dbg9na'
primary_region = 'sjc'

[build]

[[mounts]]
  source = 'searxng'
  destination = '/etc/searxng'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
